### PR TITLE
FIX for the css of the equipment page.

### PR DESCRIPTION
**Pull request by alinmigea**
ADD a new responsive css class for padding left and right.

### CODE REVIEW

**Comment by alinmigea** [comment]
@thorbenegberts

**Comment by thorbenegberts** [comment]
Hi @alinmigea,

where did you test it? the file `portfolio-item.html` should not be in use oO

**Comment by alinmigea** [comment]
@thorbenegberts could you take a look, build the website and check it also? I've change now the page (https://github.com/Hammertime-Kassel/htks/pull/54/commits/1cc909232520d4d530f61fe3861be9d706c8a9a3)

**Comment by alinmigea** [comment]
@thorbenegberts is it somehow a different page, from what I've tested it seems to work. 
Because I remember mentioning me for the _layouts/equipment-profile.html page [here](https://github.com/Hammertime-Kassel/htks/issues/18), but I think that's the specific equipment page, not the euipment list page which I intended to modify.

**Pull request closed without merging**
